"""initial schema

Revision ID: 650fa5afa409
Revises: 
Create Date: 2026-06-12 08:23:38.078384+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '650fa5afa409'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tz_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Text(), nullable=False),
    sa.Column('tz_type', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), server_default='new', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('parent_object_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('current_revision', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_examples_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_type', sa.Text(), nullable=False),
    sa.Column('scenario', sa.Text(), server_default='new', nullable=False),
    sa.Column('section_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_tz_id', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('qdrant_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_mcp_cache',
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), server_default='3600', nullable=False),
    sa.PrimaryKeyConstraint('object_key')
    )
    op.create_table('tz_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_result', sa.JSON(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tz_id'], ['tz_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_legacy_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('parsed_payload', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('legacy_date', sa.Text(), nullable=True),
    sa.Column('extracted_objects', sa.JSON(), nullable=True),
    sa.Column('confidence_low_sections', sa.JSON(), nullable=True),
    sa.Column('ingest_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tz_id'], ['tz_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('research_log', sa.JSON(), nullable=False),
    sa.Column('critic_report', sa.JSON(), nullable=True),
    sa.Column('docx_object_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tz_id'], ['tz_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tz_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tz_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('developer_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['tz_revisions.id'], ),
    sa.ForeignKeyConstraint(['tz_id'], ['tz_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tz_feedback')
    op.drop_table('tz_revisions')
    op.drop_table('tz_legacy_attachments')
    op.drop_table('tz_conversations')
    op.drop_table('tz_mcp_cache')
    op.drop_table('tz_llm_calls')
    op.drop_table('tz_examples_registry')
    op.drop_table('tz_documents')
    # ### end Alembic commands ###
