apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abap-spec-assist
  namespace: abap-spec-assist
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  ingressClassName: nginx
  rules:
    - host: tz-assist.example.com  # замените на ваш домен
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
